### PR TITLE
Prevent error on loadxml when matrix data is null

### PR DESCRIPTION
**Pull request by scaule**
This update prevent Exception ( ContextErrorException : Warning: DOMDocument::loadXML(): Empty string supplied as input ) when matrix data_text field is null in db.

### CODE REVIEW

**Comment by gggeek** [comment]
Should we not log at least a warning when finding a NULL in the db? I imagine that in the standard lifecycle of this fieldType nulls would never be stored...

**Comment by scaule** [comment]
I have null values after a migration from eZ4. 

Yes i think it's a good idea to log it too. 
I think we have to handle this error and log a warning too.

**Comment by scaule** [comment]
It's good now  : error + log warning message

**Comment by scaule** [comment]
@andrerom could you merge this on master ?

**Pull request merged**
