### PR TITLE
Invert dependency constraints

### PR DESCRIPTION
**Pull request by MarioBlazek**

### CODE REVIEW

**Comment by andrerom** [comment]
Why? :)

**Comment by MarioBlazek** [comment]
This bundle can't be installed on kernel v6, just hangs on second constraint.

**Comment by gggeek** [comment]
as in "it should be installable along with v6 but currently it stalls at installation", I guess ?

**Comment by andrerom** [comment]
Closing as #19 hopefully makes this uneeded.

**Pull request closed without merging**
